In [1]:
import pandas as pd
from pycaret.classification import setup, compare_models, tune_model, finalize_model, predict_model

# Load Linux dataset
file_path = 'dataset/system-logs/multiple-system-log-dataset/preprocessed-data/Linux_preprocessed.csv'
df = pd.read_csv(file_path)

# Check class distribution
print("Class distribution in Linux:")
print(df['error'].value_counts())

# Setup the data in PyCaret without automatic imbalance handling
setup_data = setup(data=df, target='error', session_id=42, fold=10, fix_imbalance=False, verbose=True)

# Compare and evaluate models
best_model = compare_models()
tuned_best_model = tune_model(best_model, optimize='AUC', n_iter=30)
final_model = finalize_model(tuned_best_model)

# Displaying the final model
print("Final tuned model performance for Linux:")
predict_model(final_model)

Class distribution in Linux:
0    25152
1      415
Name: error, dtype: int64

Processing:   0%|          | 0/61 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 28 candidates, totalling 280 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).
Final tuned model performance for Linux:

,timestamp,tokens,warning,Label,error,prediction_label,prediction_score
17753,Dec 3 09:46:33,"['combo', 'kernel:', 'Out', 'of', 'Memory:', '...",0,Linux,0,0,1.0
17482,Dec 2 23:35:43,"['combo', 'kernel:', 'Out', 'of', 'Memory:', '...",0,Linux,0,0,1.0
9773,Nov 20 05:40:50,"['combo', 'kernel:', 'Out', 'of', 'Memory:', '...",0,Linux,0,0,1.0
705,Jun 11 04:09:53,"['combo', 'su(pam_unix)[5961]:', 'session', 'c...",0,Linux,0,0,1.0
12292,Nov 22 01:25:26,"['combo', 'kernel:', 'Out', 'of', 'Memory:', '...",0,Linux,0,0,1.0
...,...,...,...,...,...,...,...
13327,Nov 22 22:20:23,"['combo', 'kernel:', 'Out', 'of', 'Memory:', '...",0,Linux,0,0,1.0
12133,Nov 21 18:00:20,"['combo', 'kernel:', 'Out', 'of', 'Memory:', '...",0,Linux,0,0,1.0
1311,Jun 24 18:55:18,"['combo', 'ftpd[28574]:', 'connection', 'from'...",0,Linux,0,0,1.0
17224,Dec 1 20:40:48,"['combo', 'kernel:', 'Out', 'of', 'Memory:', '...",0,Linux,0,0,1.0
12071,Nov 21 15:40:53,"['combo', 'kernel:', 'Out', 'of', 'Memory:', '...",0,Linux,0,0,1.0